# Generated by Django 5.1.6 on 2025-03-02 00:46

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(blank=True, max_length=200)),
                ('continent', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('timezone_1', models.CharField(blank=True, max_length=50)),
                ('timezone_2', models.CharField(blank=True, max_length=50)),
                ('timezone_3', models.CharField(blank=True, max_length=50)),
                ('timezone_4', models.CharField(blank=True, max_length=50)),
                ('language_1', models.CharField(blank=True, max_length=50)),
                ('language_2', models.CharField(blank=True, max_length=50)),
                ('language_3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Certificate description')),
                ('type', models.CharField(choices=[('CA', 'Calibration'), ('DE', 'Degree')], max_length=2, verbose_name='Certificate Type')),
                ('file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='files'), upload_to='certificates/')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date time')),
                ('upload', models.DateTimeField(auto_now_add=True, verbose_name='Upload date time')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REJECTED', 'Rejected'), ('WAITING', 'Waiting'), ('APPROVED', 'Approved')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Token')),
                ('due_date', models.DateField(blank=True, default='2099-12-31', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='certificate.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('customer_id', models.CharField(max_length=150, verbose_name='Customer ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Postal code')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=200, verbose_name='Address 2')),
                ('address_3', models.CharField(blank=True, max_length=200, verbose_name='Address 3')),
                ('address_4', models.CharField(blank=True, max_length=200, verbose_name='Address 4')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificate.customer')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_of', to='certificate.customer'),
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('issuer_id', models.CharField(max_length=150, verbose_name='Issuer ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Postal code')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=200, verbose_name='Address 2')),
                ('address_3', models.CharField(blank=True, max_length=200, verbose_name='Address 3')),
                ('address_4', models.CharField(blank=True, max_length=200, verbose_name='Address 4')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='certificate.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificate.issuer')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuer_of', to='certificate.issuer'),
        ),
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.issuer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
