# Generated by Django 5.1.4 on 2025-01-20 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_customer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Token'),
        ),
    ]
